name: Deploy to Hostinger

on:
  push:
    branches:
      - main # Replace with your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_SERVER_IP }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SCRIPT_AFTER: |
            cd /var/www/mehradfarahnak.info && git pull origin main
            pnpm install
            pnpm run build
            pm2 reload 1
